name: Gradle Build with Java 17

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configuración de Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # Asegurar permisos de ejecución para gradlew
      - name: Grant Execute Permission for Gradle Wrapper
        run: |
          ls -l gradlew
          chmod +x gradlew
          ls -l gradlew

      # Compilar el proyecto
      - name: Build with Gradle
        run: ./gradlew build

      # Guardar el artefacto (archivo JAR generado)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: build/libs/*.jar
